### ISSUE TITLE
Scrape project descriptions from Devpost

### ISSUE THREAD

**Issue by thisistimothychen** [bitcamp/hackathon-expo-app#1]
We want to add an expandable section for short project descriptions. On Devpost, project pages will have a description that the user can enter (e.g. https://devpost.com/software/flow-k572np). However, the CSV file that the hackathon manager can download from Devpost does not include this field (sample CSV can be found in this repo).

Our options are to:
(1) Individually make GET requests to each project on Devpost and grab the description from the HTML
or
(2) Add a custom question in Devpost so that users will have to enter in the description when they submit their project to our hackathon (this is inflexible since they can't go back and edit it, whereas (1) they can go back and make edits)

**Comment by egao7** [comment]
### Proposed Solution
From the devpost CSV I'll take the project URLs from the Devpost CSV and scrape the data using Python's requests library. Then I'll use BeautifulSoup to parse it and grab the descriptions I need. 
Then I'll take those descriptions and put it into the Project objects during initialization

### Timeline
By 2/1 finish scraping and parsing the webpages -- done
By 2/9 send all that data to the backend (and make it fit into the CSV parsing codebase section) -- done
By 2/15 finish bug-fixing and testing, try to optimize a little if needed

**Comment by thisistimothychen** [comment]
Something to consider during the admin workflow: we'll have a Devpost CSV that would get imported into our expo app from the Godmode page. We'll have project URLs for each project. Right now, these URLs aren't being used, but we can access them when we're seeding the projects from the CSV. The scraping can be integrated into the CSV parsing portion of the existing codebase.

**Comment by thisistimothychen** [comment]
BTW - here's the entrypoint to parse the CSV: https://github.com/bitcamp/hackathon-expo-app/blob/c806fa66e455f3bdd1f2d0bed51ebdecce028649/api/server.py#L148-L159

**Comment by eveninglily** [comment]
Closing this, please use gotechnica/technica-expo-app#94 going forward
