### ISSUE TITLE
[Endpoint] GET all winning projects

### ISSUE THREAD

**Issue by thisistimothychen** [bitcamp/hackathon-expo-app#2]
We want to add a UI element at the top of the public page to highlight project winners (instead of only tacking on a ribbon to the winner's project in the table).

To do this, we need an endpoint that will *efficiently* filter through all projects to get winners. This way, the frontend won't need to do the processing.

**Comment by egao7** [comment]
### Proposed Solution
Build an endpoint for project winners adhering to REST API standards. Connect with MongoDB database to retrieve and edit data. See if we can make it more efficient with specific algorithms or data structures. The UI element can be created with React and other Javascript libraries.

Winners will be chosen by sorting through the challenges and returning all the ones that have the "won":true parameter. I will look through the schema to determine the different project category winners.

### Timeline
By 2/1 create rough structure of the endpoint with GET functionality -- done
By 2/15 implement and link database to endpoint (?)
By 2/23 create UI element using React on the frontend to display data
By 3/1 tinker with design and optimize code
Test until deployment

**Comment by eveninglily** [comment]
Use gotechnica/technica-expo-app#95 going forward
