### ISSUE TITLE
Scrape Devpost for Sponsor/Challenge Info

### ISSUE THREAD

**Issue by thisistimothychen** [bitcamp/hackathon-expo-app#3]
The challenges are formatted as `Challenge Name - Company Name` (e.g. `Best Use of a Data Set - Ebay`).

Info instead of having to manually create sponsors and their challenges in the Godmode view (and double check for correctness), we can just create everything on Devpost first and then scrape the main hackathon Devpost page (e.g. https://technica2018.devpost.com/) to grab the challenge titles, split/parse/trim whitespace, and seed the database.

Pay attention to how the database schema is structured when attempting this!

**Comment by naveenr414** [comment]
## Proposed Solution: 
To solve this problem, we use a web scraper written in python to automatically retrieve data from devpost. The scraper will be written using the BeautifulSoup library. After scraping the data, the scraper will interface with the Mongo database and insert the data using the Pymongo library. 

## Timeline
January 25th - Have scraper that can gather information from devpost
February 5th - Scraper can insert information into database
February 15th - Clean up code and fix bugs

### Deadline - February 15th

**Comment by thisistimothychen** [comment]
Looks good to me!

**Comment by thisistimothychen** [comment]
Goal for resolving comments: Wednesday, February 20th
