### ISSUE TITLE
[Endpoint] Create a PUT endpoint that will reset a challenge

### ISSUE THREAD

**Issue by thisistimothychen** [bitcamp/hackathon-expo-app#4]
We want to include a reset button for each sponsor challenge in case a sponsor needs to re-submit their winners (e.g. if they want to add another winner or if they accidentally submitted the wrong one).

This endpoint needs to do the following in the DB: (1) clear out winners from the company object, (2) clear out winners from the project object that was originally a winner. Pay attention to all references - there are 2 fields in each project object that indicate winner status or not (this was a bad design decision, but for now we'll roll with it).

Refer to existing endpoint `/api/projects/id/<project_id>/makeNonWinner` - this might be as easy as verifying that this endpoint already does the job.

**Comment by spiratla12** [comment]
# Proposed Solution
I plan on creating an endpoint, which when called will clear out the winners from the company and clear out original winners. The code for this will probably be written in server.py to be consistent with the other endpoints. 

# Timeline
*By January 20th - have a full understanding of how all the endpoints in the server work
*By February 8th - hopefully be done with creating the endpoint and start testing to make sure that it's working properly
*By February 15th - hopefully be done testing!

**Comment by thisistimothychen** [comment]
Don't forget to clear out the winner status from the actual project object as well! (Kinda stupid that I made it that way, but made it more efficient in some ways, but it's bad design welp)

**Comment by thisistimothychen** [comment]
Before coding anything, try reading through the existing endpoint because that might just do everything already :)

**Comment by spiratla12** [comment]
Update:

As it turns out, the makeNonWinner endpoint does not take care of this case, as it's making a specific project a non winner, rather than resetting all winners

I created an endpoint, to help deal with this, and am currently testing!

**Comment by thisistimothychen** [comment]
Perfect, thanks for the update!
