### ISSUE TITLE
[Judging feature] - Time to spend estimate per project

### ISSUE THREAD

**Issue by thisistimothychen** [bitcamp/hackathon-expo-app#5]
We want to give judges an idea of how much time to spend judging each project to make sure the expo ends on time. This estimate is based on # of judges that the sponsor has.

Probably needs DB to store # of judges? Or maybe it's better UX to just not ask them to input anything but just use # of projects and show guideline for minutes to spend based on a few different #s like:

```
You have 30 projects to judge! Here are some time estimates on how long you should spend on each project - let us know if you need some help with judging if time is tight!
1 judge - 1.75 minutes
2 judges - 3.5 minutes
3 judges - 5.25 minutes
...etc...
```

**Comment by japsuchiha** [comment]
# Proposed Solution
We can make a UX change to the sponsor view and simply add like a popup once they log in to start judging the challenges. We can call the backend endpoint for each sponor and get the projects submitted do some simple math and post the results on the popup based on the number of judges.

# Timeline 
Will collaborate with the frontend team and see if they are making any changes to the expo frontend.
Start on it around Feb 15 
Done by Feb 22nd

**Comment by eveninglily** [comment]
Closing in favor of gotechnica/technica-expo-app#93
