### ISSUE TITLE
Increase ease of customization

### ISSUE THREAD

**Issue by thisistimothychen** [bitcamp/hackathon-expo-app#8]
Pull out the potentially customizable parameters into a single file
* Background image upload endpoint
* Color palette into a single CSS file
* Logo
* Hackathon name

**Comment by japsuchiha** [comment]
# Proposed Solution
Extend on config.py file to include background image, logo and hackatho name. Also create another CSS file which would contain the color palette and other styles required for the above.

# Timeline
- By 6th Feb go through the codebase and factor out the customizations.
- By 15th Feb write the customization file and begin testing.

**Comment by thisistimothychen** [comment]
- We'll also want to pull on any colors used as strings inside the actual JS files (I know we did that at least once for table numbers)
- For background image and logo, potentially just allow them to replace `background.jpg` (or whatever filename that was) and just include this in documentation
- Potentially make background image optional, and in the case they dont' use an image, allow customization of background color (in that custom CSS file)
- How will you separate out color palette? Might want to specify things like `accent`, `text`, `background`, etc...

**Comment by japsuchiha** [comment]
# Customization Options

## Overall

- the background
-	banners
-	logo
-	fonts
-	color scheme for text and buttons
-	winner tag
-	name
-	other hackathon images

## JS files
- Searchandfilter.js
   - toggle style and background properties added as inline styles
- table.js
   - pull out array color scheme

Hopefully not missing out anything but let me know if you think somethings missing.

**Comment by thisistimothychen** [comment]
Looks like a pretty comprehensive list to me! :D We can always add more things to this as we think of them, but I think you've covered our bases pretty well :)
Feel free to ping if you want to discuss implementation approaches, but otherwise feel free to get hacking!
